CREATE TABLE notes (
    id SERIAL PRIMARY KEY,
    contenido VARCHAR(140) NOT NULL,
    creado TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    modificado TIMESTAMP WITH TIME ZONE DEFAULT ON UPDATE CURRENT_TIMESTAMP
);


CREATE TABLE notes (
    id SERIAL PRIMARY KEY,
    contenido VARCHAR(140) NOT NULL,
    creado TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);


INSERT INTO notes (contenido) VALUES('hola a todos');